#!/bin/ksh
# author: dukun@taobao.com
#   date: 2011-11-23
#   desc: 计算出一批机器在某一天的QPS峰值
#     eg: ichosts -g L1|hsfqps
#     eg: ichosts -g L1|hsfqps -d 2011-11-11

# 计算QPS的临时脚本
typeset HSFQPS_SHELL_FILE="/tmp/hsfqps_$$.cmd";
typeset HSF_MONITOR_IPS_FILE="/tmp/hsfqps_ips_$$.cmd";
typeset HSF_MONITOR_FILE="/home/admin/logs/monitor/monitor-app-org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.log";

# 构造监控执行脚本
function build_hsfqps_shell_file
{
echo "cat $HSF_MONITOR_FILE|awk 'BEGIN{RS=\"\02\";FS=\"\01\";} \$1==\"HSF-ProviderDetail\" {m[\$7]+=\$5}END{for(i in m)printf(\"%s\t%s\n\",i,m[i])}'" > $HSFQPS_SHELL_FILE
}



# 主程序开始
function main
{

    # 解析命令行传来的参数
    typeset local cmd_arg_exp=$(getopt -o hd: --long help,date: -- ${@})
    if [[ $? != 0 ]];then
        show_help;
        exit "$ERROR_CODE_CHECK_ARGS";
    fi
    eval set -- "$cmd_arg_exp";

    while true;
    do
        case ${1} in
            -d|--date)
                HSF_MONITOR_FILE="$HSF_MONITOR_FILE.""$2"
                shift 2;
            ;;
            -h|--help)
                init;
                show_help;
                shift;
                exit;
            ;;
            --)
                shift;
                break;
            ;;
        esac;
    done;

    build_hsfqps_shell_file

	while read ip;
	do
		cat "$HSFQPS_SHELL_FILE"|xssh -i "$ip"
	done\
		|awk '{m[$2]+=$3}END{for(i in m)print i"\t"m[i]}'\
    	|awk -F ":|\t" '{m[$1":"$2]+=$4}END{for(i in m)print i"\t"m[i]/120}'\
        |sort -nk2\
        |tail -1

}

main "$@"


rm -f $HSFQPS_SHELL_FILE
rm -f $HSF_MONITOR_IPS_FILE
